### ISSUE TITLE
Perimeter, а не Perimetr

### ISSUE THREAD

**Issue by coursar** [radikzoom/wallpaper-roll#3]
https://github.com/radikzoom/wallpaper-roll/blob/43180608b13acf5e885a34d6f841ab00dc02dc75/src/MainR.java#L4

**Comment by radikzoom** [comment]
https://github.com/radikzoom/wallpaper-roll/blob/73863646b12927c2f12d5ddd4a6247c302079272/src/MainR.java#L3-L8
fix
